### PR TITLE
refactor csproj

### PR DESCRIPTION
**Pull request by microlith57**
- uses https://github.com/swoolcock/CelesteModTemplate as a template
- includes stripped celestenet dlls
- updated monomod version
- added CopyFiles rule and everest.yaml that points to this

### CODE REVIEW

**Comment by Brokemia** [comment]
I've tried this out and it seems to work, however, I'm not so sure about the inclusion of an everest.yaml inside the project. I would have to restructure the mod to have the code be the root of the project, and I'm not sure I want to do that.

**Comment by microlith57** [comment]
when i put that in i hadn't looked at the structure of the .zip mod; i'll remove the everest.yaml i added in favour of the existing one. you will probably have to change the dll path though

**Comment by microlith57** [comment]
ready for review again!

**Comment by Brokemia** [comment]
Looks good and builds on my end

**Pull request merged**
